name: Publish to GitHub

on:
  release:
    types:
      - published

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Build'
        run: npm run build

      - name: Authenticate with Registry
        run: |
          echo "@frankfoerster:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
          echo "" >> .npmrc
          npm whoami --registry https://npm.pkg.github.com
        env:
          NPM_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_NPM }}

      - name: "Publish"
        run: npm publish
